server:
  servlet:
    context-path: /sell
  port: 8080



spring:
  profiles:
    active: dev
  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://www.zhanke.site/sell?useSSL=false&serverTimeZone=UTC&useOldAliasMetadataBehavior=true
    username: zhanke
    password: zhanke1234
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  freemarker:
    suffix: .ftl

#定义网址
project-url:
  sell: localhost:8080
  wechat-mp-authorize: https://api.weixin.qq.com/sns/jscode2session
#  wechat-mp-authorize: https://api.weixin.qq.com/sns/oauth2/access_token
wechat:
  mp-app-id: wx7bea734df0ceb778
  mp-app-secret: 0eedbe06d32cfc6c4865af78b2455713
  user-info-url: https://api.weixin.qq.com/sns/userinfo

